# Uncomment this line to define a global platform for your project
# platform :ios, ‘7.0’

source 'https://github.com/CocoaPods/Specs.git'

target 'StackQA' do
pod 'MagicalRecord'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'AFNetworking'
pod 'MBProgressHUD'
pod 'UICKeyChainStore'
pod 'RDRStickyKeyboardView'
pod 'UICKeyChainStore'
pod 'UIImage-ResizeMagick'
pod 'BENTagsView'
pod 'UIScrollView-InfiniteScroll'
end

target 'StackQATests' do
pod 'OCMockito'
pod 'Nocilla'
pod 'Kiwi'
pod 'OHHTTPStubs'
end

